// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD4O-hIXRl5mtz3IPhxP8gtv6DWlumwQc',
    appId: '1:3830007452:web:e640b7051b4519857d8f59',
    messagingSenderId: '3830007452',
    projectId: 'fir-login-app-e42b0',
    authDomain: 'fir-login-app-e42b0.firebaseapp.com',
    storageBucket: 'fir-login-app-e42b0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbCDAaGoPZETNSBtOroQXNT6XPGnLz85w',
    appId: '1:3830007452:android:76d288de76d5abde7d8f59',
    messagingSenderId: '3830007452',
    projectId: 'fir-login-app-e42b0',
    storageBucket: 'fir-login-app-e42b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkmVYe3csCCLcXhlP0CnwPt0AO92eaZK0',
    appId: '1:3830007452:ios:0d52a70f9ee2d4767d8f59',
    messagingSenderId: '3830007452',
    projectId: 'fir-login-app-e42b0',
    storageBucket: 'fir-login-app-e42b0.appspot.com',
    iosBundleId: 'org.teKsafari.firebaseloginapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkmVYe3csCCLcXhlP0CnwPt0AO92eaZK0',
    appId: '1:3830007452:ios:b59e628d55f432a87d8f59',
    messagingSenderId: '3830007452',
    projectId: 'fir-login-app-e42b0',
    storageBucket: 'fir-login-app-e42b0.appspot.com',
    iosBundleId: 'org.teKsafari.firebaseloginapp.RunnerTests',
  );
}
